# Assignment
- 중간 중간 assignment라고 되어있고 ''' ? ''' 이 있을거에요 그 부분을 채워주시면 됩니다

# Assignment 1 : Gaussian Naive Bayes Classification 해보기

- sklearn에 Gaussian Naive Bayes Classification 클래스 함수가 이미 있습니다

- 그것을 활용하여 간단하게 예측만 하시면 됩니다

- 필요 함수 링크를 주석으로 처리하여 첨부했으니 보시고 사용해주세요

In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.datasets import load_iris

- sklearn에 내장되어있는 붓꽃 데이터를 사용할 겁니다

In [3]:
iris = load_iris()

- 붓꽃데이터를 불러옵니다

In [4]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

- 설명변수 x가 꽃받침 길이, 꽃받침 폭 , 꽃잎 길이 , 꽃잎 폭 임을 알 수 있습니다
- sepal length , sepal width , petal length , petal width
- 타겟변수 y는 붓꽃의 품종으로 총 3가지의 종류가 있는 걸 알 수 있습니다
- Iris-Setosa , Iris-Versicolour , Iris-Virginica 가 0 1 2 로 분류되어 있습니다

In [5]:
X = pd.DataFrame(iris.data)
y = pd.DataFrame(iris.target)

 - 설명변수 x와 타겟변수 y를 판다스의 데이터프레임 형태로 만듭니다

In [6]:
X

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [7]:
y

0
0    0
1    0
2    0
3    0
4    0
..  ..
145  2
146  2
147  2
148  2
149  2

[150 rows x 1 columns]

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

- 가우시안 나이브 베이즈 함수를 불러옵니다

# 1-1) assignment
- train set과 test set을 80 대 20의 비율로 나누어 주세요
- https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html
- 해당 함수를 사용하시고 사용 후에 주석으로 해당 함수에 어떤 인자들이 있는지 설명해주세요

In [10]:
# X, y 를 8 : 2 비율로 train 과 test 데이터로 분할
# test_size : 전체 데이터에 대한 test 데이터의 비율
# random_state : 시드값, test 와 train 데이터를 구분하는 기준에 대한 random 시드값
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 48)

# 1-2) assignment
- 가우시안 나이브 베이즈 함수를 사용하여 학습을 시킨 후 score 값을 계산하여 주세요
- 모두 GaussianNB 클래스 안에 메서드로 들어있습니다
- https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.GaussianNB.html
- 해당 함수를 사용하시고 사용 후에 주석으로 해당 함수에 어떤 인자들이 있는지 설명해주세요

In [18]:
gnb = GaussianNB() # 모델 생성
y_pred = gnb.fit(X_train, y_train).predict(X_test) # X_train 과 y_train 으로 모델을 학습, X_test로 예측한 값을 y_pred 로
y_pred # 예측한 값은 [0,1,2]로 label 값이 부여되어있음

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/naive_bayes.py:206: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([1, 1, 1, 0, 2, 2, 0, 2, 0, 1, 2, 0, 0, 2, 1, 1, 0, 1, 1, 2, 0, 2,
       2, 1, 2, 0, 0, 2, 2, 1])

In [24]:
y_proba = gnb.predict_proba(X_test)
y_proba # proba 는 예측 라벨에 대한 각각의 확률을 보여주며, 가장 높은 확률의 라벨로 분류됨

array([[5.33381861e-071, 9.99858461e-001, 1.41538896e-004],
       [1.07973929e-088, 9.99266970e-001, 7.33030329e-004],
       [1.73695125e-139, 5.52078337e-001, 4.47921663e-001],
       [1.00000000e+000, 2.62763927e-015, 1.07964621e-023],
       [2.35285806e-117, 6.91576790e-002, 9.30842321e-001],
       [1.59242928e-155, 7.45210954e-004, 9.99254789e-001],
       [1.00000000e+000, 3.80431368e-018, 7.71664901e-025],
       [3.74189346e-118, 9.77839267e-002, 9.02216073e-001],
       [1.00000000e+000, 7.70903347e-021, 2.86636235e-026],
       [2.30821263e-064, 9.99973793e-001, 2.62067333e-005],
       [9.06635215e-155, 7.28285533e-004, 9.99271714e-001],
       [1.00000000e+000, 1.40378552e-018, 1.88662559e-025],
       [1.00000000e+000, 3.52348507e-016, 2.87132598e-023],
       [1.83270429e-119, 1.03120129e-001, 8.96879871e-001],
       [3.56423693e-082, 9.99577137e-001, 4.22863047e-004],
       [3.60026322e-104, 5.86983263e-001, 4.13016737e-001],
       [1.00000000e+000, 6.63206722e-018

In [38]:
# 
gnb.score(X_test, y_test)

0.9

# Assignment 2 : Naive Bayes Classification 해보기
- 제가 임의로 만든 데이터 셋입니다
- spam 메세지에 gamble money hi라는 단어의 유무를 기준으로 0과 1을 주었고 spam 메세지인지 아닌지를 spam에 0과1로 정해주었습니다
- 설명변수는 gamble, money, spam 이고 종속변수는 spam입니다

In [40]:
gamble_spam = {'gamble' : [1,0,1,0,1,0,0,0,1,0,0,0,1,1,1,1,0,1,0,0,0,0,0,0,0,
                           1,0,1,1,0,1,0,1,0,1,1,1,1,0,0,0,1,0,1,0,1,0,1,0,1,
                           0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,1,1,0,1,1,1,1,1,0,0,
                           1,0,0,1,0,0,0,1,1,0,1,0,1,1,0,0,0,1,0,1,1,1,0,1,1],
               'money' : [1,1,1,0,1,0,0,0,1,0,0,0,1,0,1,1,0,1,1,0,1,1,1,1,1,
                          0,0,0,1,1,1,0,0,0,1,1,0,0,0,1,0,1,1,0,1,0,0,1,0,1,
                          1,0,1,1,0,1,0,1,0,1,1,0,0,0,1,1,0,0,0,1,1,1,1,1,1,
                          1,1,0,1,0,1,1,0,0,1,0,1,1,1,1,0,0,1,0,0,1,0,0,1,0],
               'hi' : [0,1,0,1,0,1,0,0,1,0,0,0,1,0,1,1,1,0,1,1,1,0,0,0,0,
                       1,0,0,1,0,0,0,1,0,1,1,1,0,1,1,1,0,0,1,0,1,0,1,1,0,
                       1,0,0,0,1,1,1,1,0,1,0,1,1,0,0,1,1,1,1,0,0,0,0,0,0,
                       1,1,0,0,0,1,1,0,1,0,1,1,0,0,0,0,0,0,1,0,0,0,1,0,0],
                'spam' : [1,0,1,0,1,0,0,0,1,0,0,0,1,1,1,1,0,1,1,0,0,0,1,1,0,
                          1,0,1,1,0,0,1,1,0,0,0,0,1,1,0,1,0,0,1,0,1,0,1,0,1,
                          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,0,0,0,0,
                          1,0,0,1,0,0,0,1,1,0,1,0,1,1,0,0,0,1,0,1,1,1,0,1,1]}

- 해당 딕셔너리 데이터를 판다스 데이터 프레임으로 변경하여줍니다

In [53]:
df  = pd.DataFrame(gamble_spam, columns = ['gamble', 'money', 'hi', 'spam'])

In [59]:
df.head()

gamble  money  hi  spam
0       1      1   0     1
1       0      1   1     0
2       1      1   0     1
3       0      0   1     0
4       1      1   0     1

# 2-1) assignment
- 해당 판다스 데이터프레임 형식을 numpy array형식으로 변환해 주세요
- https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.as_matrix.html

In [49]:
spam_data = df.values

In [52]:
spam_data

array([[1, 1, 0, 1],
       [0, 1, 1, 0],
       [1, 1, 0, 1],
       [0, 0, 1, 0],
       [1, 1, 0, 1],
       [0, 0, 1, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 1, 1, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [0, 0, 1, 0],
       [1, 1, 0, 1],
       [0, 1, 1, 1],
       [0, 0, 1, 0],
       [0, 1, 1, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 0],
       [1, 0, 1, 1],
       [0, 0, 0, 0],
       [1, 0, 0, 1],
       [1, 1, 1, 1],
       [0, 1, 0, 0],
       [1, 1, 0, 0],
       [0, 0, 0, 1],
       [1, 0, 1, 1],
       [0, 0, 0, 0],
       [1, 1, 1, 0],
       [1, 1, 1, 0],
       [1, 0, 1, 0],
       [1, 0, 0, 1],
       [0, 0, 1, 1],
       [0, 1, 1, 0],
       [0, 0, 1, 1],
       [1, 1, 0, 0],
       [0, 1, 0, 0],
       [1, 0, 1, 1],
       [0, 1, 0, 0],
       [1, 0, 1, 1],
       [0, 0, 0, 0],
       [1, 1,

# 2-2) assignment
- P(spam=1), P(spam=0)
- P(gamble=1|spam=1), P(money=1|spam=1), P(hi=1|spam=1)
- P(gamble=1|spam=0), P(money=1|spam=0), P(hi=1|spam=0)
- 위의 확률들을 구하여 주세요

- 먼저 P(spam)의 확률 부터 구해주세요
- P(spam=1)인 경우만 제가 완성을 해두었습니다 참고하시면 금방 금방 채우실거에요 :)

In [56]:
p_spam = sum(spam_data[:,3]==1)/len(spam_data) # P(spam=1)
p_spam_not = sum(spam_data[:,3]==0) / len(spam_data) # P(spam=0)

- gamble , money , hi의 조건부 확률을 다 구해주세요
- P(gamble=0|spam=1) = 1 - P(gamble=1|spam=1) 의 형태로 구하면 되므로 굳이 따로 구하지 않습니다
- 각 값이 어떤 조건부 확률인지 이름만으로는 알기 어려울거같아 바로 옆에 주석을 달아놨습니다 참고하세요
- 위랑 마찮가지로 제일 위에 껀 제가 해놨어요 참고해서 한번 구해보세요

In [74]:
# a 번째 배열이 b 일 때, x 번째 배열이  y 일 확률
def getProb(x,y,a,b):
    prob = sum((spam_data[:,x] == y) & (spam_data[:,a] == b)) / sum(spam_data[:,a] == b)
    return prob

In [79]:
# gamble : 0, money : 1, hi : 2, spam : 3
print(p_gamble_spam_not)
print(getProb(0,1,3,0))

print(p_gamble_spam)
print(getProb(0,1,3,1))

0.1896551724137931
0.1896551724137931
0.8333333333333334
0.8333333333333334


In [80]:
p_gamble_spam = sum((spam_data[:, 0] == 1) & (spam_data[:, 3] == 1)) / sum(spam_data[:, 3] == 1) # P(gamble=1|spam=1), spam 이 1일 때, gamble 이 1인 경우
p_gamble_spam_not = sum((spam_data[:,0] == 1) & (spam_data[:,3] == 0)) / sum(spam_data[:,3] == 0)  # P(gamble=1|spam=0), spam 이 0일 때, gamble 이 1인 경우

p_money_spam = getProb(1,1,3,1) # P(money=1|spam=1), spam 이 1일 때, money 가 1인 경우
p_money_spam_not = getProb(1,1,3,0) # P(money=1|spam=0), spam 이 0일 때, money 가 1인 경우

p_hi_spam = getProb(2,1,3,1) # P(hi=1|spam=1), spam 이 1일 때, hi 가 1인 경우
p_hi_spam_not = getProb(2,1,3,0) # P(hi=1|spam=0), spam 이 0일 때, hi 가 1인 경우

- 이제 P(*|spam=1)값 리스트와 P(*|spam=0)값 리스트를 생성해줍니다

In [81]:
proba = [p_gamble_spam,p_money_spam,p_hi_spam] # spam = 1 일 때, 각 독립변수가 1 일 확률
proba_not = [p_gamble_spam_not,p_money_spam_not,p_hi_spam_not] # spam = 0 일 때, 각 독립변수가 1 일 확률

In [87]:
print(proba)
print(proba_not)

[0.8333333333333334, 0.5476190476190477, 0.4523809523809524]
[0.1896551724137931, 0.5344827586206896, 0.4482758620689655]


- 요건 테스트 셋이에요
- 예를 들어 [0,1,0]인 경우 gamble=0,money=1,hi=0인 경우에 spam인지 아닌지 확률을 계산해 달라는 의미 입니다
- 설명변수가 3개 밖에 안되기때문에 [0,0,0] ~ [1,1,1] 8가지 모든 경우에 대해 확률 P(*|spam=1)를 구할 거에요

In [82]:
test = [[i,j,k] for i in range(2) for j in range(2) for k in range(2)]

In [83]:
test

[[0, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 1],
 [1, 0, 0],
 [1, 0, 1],
 [1, 1, 0],
 [1, 1, 1]]

# 2-3) assignment
- 조건부 확률을 구하는 함수를 구해주세요

- x는 해당 독립변수가 0인지 1인지를 받는 인자이구요
- p는 해당독립변수가 1일때의 조건부 확률이 들어갑니다
- P(X=x|Y=1) = x*P(X=1|Y=1)+(1-x)*P(X=0|Y=1)을 응용하세요

In [129]:
print(proba)
print(proba_not)

[0.8333333333333334, 0.5476190476190477, 0.4523809523809524]
[0.1896551724137931, 0.5344827586206896, 0.4482758620689655]


In [176]:
test

[[0, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 1],
 [1, 0, 0],
 [1, 0, 1],
 [1, 1, 0],
 [1, 1, 1]]

- test경우에 대해 각 확률을 반환해주는 함수를 생성해주세요

In [198]:
# 0 * 독립변수의 조건부확률 + 1 * 독립변수의 조건부확률
def con_proba(x,p):
    value = np.dot(x,p) + np.dot(1-x, 1-p)
    return value

In [199]:
def process(p_spam,p_spam_not,test,proba,proba_not):
    result = []
    for i in range(8):
        a = p_spam
        b = p_spam_not
        for j in range(3):
            a = a*con_proba(test[i][j], proba[j])
            b = b*con_proba(test[i][j], proba_not[j])
        summation = a+b
        result.append([a/summation,b/summation])
    return result

- 결과 입니다 다음과 같은 값들이 똑같이 나오면 과제 성공이에요
- 왼쪽이 spam 메세지일 확률, 오른쪽이 spam 메세지가 아닐 확률입니다
- gamble money hi라는 단어가 들어가면 들어갈수록 spam메세지인걸 알수가 있네요
- spam 메세지일 확률이 0.5를 넘기는 아래에서 6,7,8행의 경우가 spam 메세지로 분류가 되겠네요
- 즉 gamble이라는 단어와 money 혹은 hi라는 단어가 하나라도 같이 있으면 spam메세지가 되나봐요

In [200]:
process(p_spam,p_spam_not,test,proba,proba_not)

[[0.12561158047604412, 0.8743884195239557],
 [0.1274444080172175, 0.8725555919827824],
 [0.13153830892959942, 0.8684616910704006],
 [0.1334444168893966, 0.8665555831106035],
 [0.7542408952456084, 0.24575910475439156],
 [0.757301978407486, 0.24269802159251405],
 [0.7639150506833852, 0.23608494931661472],
 [0.7668928774284339, 0.233107122571566]]