In [35]:
import numpy as np

In [36]:
X = [[2.7810836,2.550537003],
    [1.465489372,2.362125076],
    [3.396561688,4.400293529],
    [1.38807019,1.850220317],
    [3.06407232,3.005305973],
    [7.627531214,2.759262235],
    [5.332441248,2.088626775],
    [6.922596716,1.77106367],
    [8.675418651,-0.242068655],
    [7.673756466,3.508563011]]

In [37]:
input_size = len(X[0]) # 10
hidden_size = 3
output_size = 2
std=1e-4

In [38]:
W1 = std * np.random.randn(input_size, hidden_size)
b1 = np.random.randn(hidden_size)
W2 = std * np.random.randn(hidden_size, output_size)
b2 = np.random.randn(output_size)

In [39]:
np.array(X).shape

(10, 2)

In [40]:
W1.shape, b1.shape, W2.shape, b2.shape

((2, 3), (3,), (3, 2), (2,))

In [41]:
h = np.dot(X,W1) + b1

In [42]:
h

array([[3.06046118, 0.3307517 , 0.90638635],
       [3.06040624, 0.33067589, 0.90616172],
       [3.0601188 , 0.33080744, 0.90659026],
       [3.06050765, 0.33066566, 0.90612041],
       [3.06038645, 0.33077277, 0.90645791],
       [3.06076501, 0.33102537, 0.90718662],
       [3.06074061, 0.33088919, 0.90677557],
       [3.06092096, 0.33097454, 0.90701649],
       [3.06146726, 0.33104947, 0.90718876],
       [3.06061175, 0.33103659, 0.90723617]])

In [43]:
h.shape

(10, 3)

In [44]:
np.maximum(h,0)

array([[3.06046118, 0.3307517 , 0.90638635],
       [3.06040624, 0.33067589, 0.90616172],
       [3.0601188 , 0.33080744, 0.90659026],
       [3.06050765, 0.33066566, 0.90612041],
       [3.06038645, 0.33077277, 0.90645791],
       [3.06076501, 0.33102537, 0.90718662],
       [3.06074061, 0.33088919, 0.90677557],
       [3.06092096, 0.33097454, 0.90701649],
       [3.06146726, 0.33104947, 0.90718876],
       [3.06061175, 0.33103659, 0.90723617]])

In [45]:
mask = (h <= 0)
a = h.copy()
a[mask] = 0

In [46]:
a

array([[3.06046118, 0.3307517 , 0.90638635],
       [3.06040624, 0.33067589, 0.90616172],
       [3.0601188 , 0.33080744, 0.90659026],
       [3.06050765, 0.33066566, 0.90612041],
       [3.06038645, 0.33077277, 0.90645791],
       [3.06076501, 0.33102537, 0.90718662],
       [3.06074061, 0.33088919, 0.90677557],
       [3.06092096, 0.33097454, 0.90701649],
       [3.06146726, 0.33104947, 0.90718876],
       [3.06061175, 0.33103659, 0.90723617]])

In [47]:
a.shape

(10, 3)

In [48]:
h2 = np.dot(a, W2) + b2

In [49]:
h2

array([[0.83120607, 0.18389506],
       [0.83120611, 0.18389511],
       [0.83120605, 0.18389505],
       [0.83120612, 0.18389511],
       [0.83120606, 0.18389505],
       [0.83120594, 0.18389486],
       [0.83120601, 0.18389494],
       [0.83120597, 0.18389487],
       [0.83120594, 0.18389477],
       [0.83120594, 0.18389486]])

In [50]:
h2.shape

(10, 2)

In [51]:
o = np.exp(h2 - np.max(h2, axis = 1).reshape(-1, 1))

In [52]:
o

array([[1.        , 0.52345144],
       [1.        , 0.52345145],
       [1.        , 0.52345145],
       [1.        , 0.52345144],
       [1.        , 0.52345144],
       [1.        , 0.5234514 ],
       [1.        , 0.52345141],
       [1.        , 0.5234514 ],
       [1.        , 0.52345136],
       [1.        , 0.52345141]])

In [54]:
p = np.exp(o)/np.sum(np.exp(o),axis=1).reshape(-1,1) 

In [55]:
p

array([[0.61693254, 0.38306746],
       [0.61693254, 0.38306746],
       [0.61693253, 0.38306747],
       [0.61693254, 0.38306746],
       [0.61693254, 0.38306746],
       [0.61693255, 0.38306745],
       [0.61693254, 0.38306746],
       [0.61693255, 0.38306745],
       [0.61693256, 0.38306744],
       [0.61693254, 0.38306746]])

In [58]:
X = [[2.7810836,2.550537003,0],
    [1.465489372,2.362125076,0],
    [3.396561688,4.400293529,0],
    [1.38807019,1.850220317,0],
    [3.06407232,3.005305973,0],
    [7.627531214,2.759262235,1],
    [5.332441248,2.088626775,1],
    [6.922596716,1.77106367,1],
    [8.675418651,-0.242068655,1],
    [7.673756466,3.508563011,1]]

In [59]:
y = []
for row in X:
    y.append(row[-1])

In [60]:
y

[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]

In [61]:
n = np.array(X).shape[0]

log_likelihood = 0
# Cross entropy : 음의 로그우도의 기대값
log_likelihood -= np.log(p[np.arange(n), y]).sum()
# N개의 자료에 대한 오차의 합계이므로
# 이를 하나의 자료에 대한 오차로 표현하기 위해 N으로 나눔
Loss = log_likelihood / n

In [62]:
log_likelihood = 0
i = 0
for q in y:
    log_likelihood -= np.log(p[i,q])
    print(p[i,q])
    i += 1

0.6169325375827042
0.6169325355499803
0.6169325341933234
0.6169325366643011
0.61693253699932
0.3830674537332074
0.3830674564368444
0.3830674526363656
0.383067444349516
0.38306745549164245


In [63]:
log_likelihood

7.212698958772967

In [64]:
log_likelihood / n

0.7212698958772967

In [65]:
Loss

0.7212698958772967

In [66]:
dp = p
for i in range(p.shape[0]):
    for j in range(p.shape[1]):
        if(j==y[i]):
            dp[i][j]-=1

In [67]:
dp

array([[-0.38306746,  0.38306746],
       [-0.38306746,  0.38306746],
       [-0.38306747,  0.38306747],
       [-0.38306746,  0.38306746],
       [-0.38306746,  0.38306746],
       [ 0.61693255, -0.61693255],
       [ 0.61693254, -0.61693254],
       [ 0.61693255, -0.61693255],
       [ 0.61693256, -0.61693256],
       [ 0.61693254, -0.61693254]])

In [278]:
da = np.heaviside(a,0)

In [279]:
a

array([[1.26190081, 0.        , 0.        ],
       [1.26184743, 0.        , 0.        ],
       [1.26197689, 0.        , 0.        ],
       [1.26182976, 0.        , 0.        ],
       [1.26192431, 0.        , 0.        ],
       [1.26208337, 0.        , 0.        ],
       [1.26198033, 0.        , 0.        ],
       [1.26202903, 0.        , 0.        ],
       [1.26203446, 0.        , 0.        ],
       [1.26210679, 0.        , 0.        ]])

In [280]:
da

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [281]:
temp = p.copy()
temp[np.arange(len(y)), y] -= 1
temp /= 10

In [282]:
temp

array([[-0.1278159,  0.0278159],
       [-0.1278159,  0.0278159],
       [-0.1278159,  0.0278159],
       [-0.1278159,  0.0278159],
       [-0.1278159,  0.0278159],
       [ 0.0721841, -0.1721841],
       [ 0.0721841, -0.1721841],
       [ 0.0721841, -0.1721841],
       [ 0.0721841, -0.1721841],
       [ 0.0721841, -0.1721841]])

In [283]:
daTemp = temp.dot(W2.T)

In [284]:
daTemp

array([[-1.43006124e-05,  6.27276508e-07, -2.10554665e-06],
       [-1.43006124e-05,  6.27276501e-07, -2.10554663e-06],
       [-1.43006124e-05,  6.27276519e-07, -2.10554667e-06],
       [-1.43006124e-05,  6.27276498e-07, -2.10554663e-06],
       [-1.43006124e-05,  6.27276511e-07, -2.10554665e-06],
       [-1.66351606e-05,  1.06318843e-05, -2.07106268e-05],
       [-1.66351606e-05,  1.06318843e-05, -2.07106268e-05],
       [-1.66351606e-05,  1.06318843e-05, -2.07106268e-05],
       [-1.66351606e-05,  1.06318843e-05, -2.07106268e-05],
       [-1.66351606e-05,  1.06318843e-05, -2.07106269e-05]])