## 1. X를 정수로 입력받은 후 1를 더한 값을 출력하시오.

In [1]:
X = int(input())

print(X+1)

 5


6


## 2. 승현이는 갓빅스 광고판 제작자이다. 승현이는 성격이 각지기 때문에 자기가 세워놓은 사각형 광고판을 가리는 걸 싫어한다. 그러던 어느날 광고판 경쟁업체 바이아즈와 베이타민에서 광고판을 가렸다는 사실을 알게 되었다. 승현이를 도와 각 광고판이 가리지 않은 부분의 넓이를 구해주자. 

입력

첫번째 줄에는 갓빅스의 광고판의 왼쪽 아래 좌표와 오른쪽 위 좌표가 주어진다. 좌표의 범위는 -100~100 까지이다.

a, b, c, d (a, b), (c, d)

그리고 두, 세번째 줄에는 각각 바이아즈와 베이타민 광고판의 왼쪽 아래 좌표와 오른쪽 위 좌표가 주어진다. 

출력 

좌표가 주어졌을 때 각 갓빅스 사각형의 가리지 않은 부분의 넓이를 구해주자.

예제 입력 1

1 2 3 5

6 0 10 4

2 1 8 3

예제 출력 1

5

In [158]:
import random

In [ ]:
# a : 깃빅스 광고판 좌표
# b : 바이아즈 광고판 좌표
# c : 베이타민 광고판 좌표

In [241]:
# 좌표 랜덤 부여
a = random.sample(range(-100,100),4)
b = random.sample(range(-100,100),4)
c = random.sample(range(-100,100),4)

In [285]:
a = [1,2,3,5]
b = [6,0,10,4]
c = [2,1,8,3]

In [286]:
# 재정렬 함수 (x1,y1,x2,y2)
# 왼쪽 하단, 오른쪽 상단 기준
def sortList(x):
    if x[0] > x[2]:
        temp = x[2]
        x[2] = x[0]
        x[0] = temp
    if x[1] > x[3]:
        temp2 = x[3]
        x[3] = x[1]
        x[1] = temp2
    return x

In [287]:
# 갓빅스 광고판 넓이 구하기
def getArea(x):
    area = abs(x[2] - x[0]) * abs(x[3] - x[1])
    return area

In [293]:
# 갓빅스와 두 광고판이 각각 겹치는 부분
# 아예 겹치는 않을 때 고려해야함
def getInter(x,y):
    if x[0] > y[2] or x[3] < y[1] or x[2] < y[0] or x[1] > y[3]:
        inter = 0
    else:
        inter = abs(min(x[2],y[2]) - max(x[0], y[0])) * abs(min(x[3], y[3]) - max(x[1], y[1]))
    return inter

In [289]:
# 바이아즈와 베이타민이 겹치는 부분
def getDuple(x,y,z):
    if getInter(a,b) == 0 or getInter(a,c) == 0:
        duple = 0
    else:
        duple = abs(min(x[2], y[2], c[2]) - max(x[0], y[0], z[0])) * abs(min(x[3], y[3], z[3]) - max(x[1], y[1], z[1]))
    return duple

In [295]:
getInter(a,c)

1

In [296]:
sortList(a)
sortList(b)
sortList(c)

print('a의 좌표는 :', a)
print('b의 좌표는 :', b)
print('c의 좌표는 :', c)
print('a의 넓이는 : ', getArea(a))
(print('가리지 않은 a의 넓이는 : ', getArea(a) - (getInter(a,b) + getInter(a,c) - getDuple(a,b,c))))

a의 좌표는 : [1, 2, 3, 5]
b의 좌표는 : [6, 0, 10, 4]
c의 좌표는 : [2, 1, 8, 3]
a의 넓이는 :  6
가리지 않은 a의 넓이는 :  5


## 수아는 투빅스 천재 해커이다. 그래서 비밀번호에 특수문자가 들어가는 걸 매우 싫어한다. 수아가 만든 비밀번호에 숫자 혹은 영어 알파벳이 아닌 특수문자를 제거하는 프로그램을 만들어 보자.

In [251]:
import re

In [252]:
# 텍스트에 포함되어 있는 특수 문자 제거
def cleanText(readData):
    text = re.sub('[-=+,#/\?:^$.@*\"※~&%ㆍ!』\\‘|\(\)\[\]\<\>`\'…》]', '', readData)
    return text

In [254]:
data = cleanText('Overwatch1!')
print(data)

data = cleanText('Overwatch1')
print(data)

Overwatch1
Overwatch1


In [282]:
a = input().split()

 1 2 3 4


In [279]:
i = 0
for x in a:
    a[i] = int(x)
    i += 1

In [283]:
def changeInt(x):
    i = 0
    for y in x:
        x[i] = int(y)
        i += 1
    return x

In [284]:
changeInt(a)

[1, 2, 3, 4]

In [2]:
import numpy as np

In [3]:
a = np.arange(1,5)

In [4]:
sum(a)

10

In [13]:
def f(prices):
    profit = 0
    max_profit = prices[len(prices) - 1]
    
    for i in range(len(prices)-2, -1, -1):
        if prices[i] < max_profit:
            profit += max_profit - prices[i]
        else:
            max_profit = prices[i]
    return profit

In [20]:
a = np.array([5,3,2])

In [21]:
f(a)

0

In [23]:
a[2]

2

In [25]:
a = np.arange(1,20)

In [28]:
a[-5:]

array([15, 16, 17, 18, 19])

In [29]:
STDIN = input().split('\n')

 ㄴ


In [31]:
a[5.0:]

TypeError: slice indices must be integers or None or have an __index__ method

In [32]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [33]:
np.where(a == 2)

(array([1]),)

In [38]:
list(a).index(3)

2

In [37]:
a.index(3)

AttributeError: 'numpy.ndarray' object has no attribute 'index'

In [40]:
b = list(a)

In [62]:
list(map(lambda x : abs(x-2.5), b))

[1.5,
 0.5,
 0.5,
 1.5,
 2.5,
 3.5,
 4.5,
 5.5,
 6.5,
 7.5,
 8.5,
 9.5,
 10.5,
 11.5,
 12.5,
 13.5,
 14.5,
 15.5,
 16.5]

In [61]:
min(list(map(lambda x : abs(x-2.5), b)))

0.5

In [63]:
0.5 + 2.5, 2.5 - 0.5

(3.0, 2.0)

In [68]:
x = 50
q = [10, 49, 177, 364, 608, 669, 850, 966, 1025, 1160, 1259, 1399, 1500]

a = [i for i in q if x > i]

In [69]:
a

[10, 49]

In [72]:
a[-1]

49

In [75]:
q[q.index(a[-1]) + 1]

177

In [81]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

# 만약 새로운 이벤트가 전 이벤트와 똑같은 양이라면, 가격은 똑같을 것이다
# 양이 더 많거나 적으면 가장 가깝게 적거나 많은 곳에서 부터 가격을 선형적으로 참고한다
# 데이터베이스가 1개의 데이터만 가지고 있으면,
# 필요한 양이 너무 작거나 너무 크면 가장 가까운 2점을 참고해 선형적으로 추론한다
# 
# import numpy as np
# import sys
# stdin = [line.strip() for line in sys.stdin]
stdin = [2000
            ,5
            ,10
            ,25
            ,50
            ,100
            ,500
            ,5
            ,27.32
            ,23.13
            ,21.25
            ,18.0
            ,15.5]

def interpolate(stdin):
    x = int(stdin[0]); n = int(stdin[1])
    quantity = list(map(int,stdin[2:2+n])); price = list(map(float, stdin[-n:]))

    if n == 1:
        res = float(price)
    elif quantity.count(x) != 0:
        res = price[quantity.index(x)]
    elif max(quantity) > x > min(quantity):
        a = [i for i in quantity if x > i]
        ma, mb = a[-1], quantity[quantity.index(a-1) + 1]
        res = ((price[quantity.index(ma)] - price[quantity.index(mb)]) / (ma - mb)) * (x - mb) + price[quantity.index(mb)]
    else:
        if x > max(quantity):
            print(quantity)
            print('X')
            ma, mb = quantity[-2], quantity[-1]
            print(ma, mb)
            print(price)
            res = ((price[quantity.index(ma)] - price[quantity.index(mb)]) / (ma - mb)) * (x - mb) + price[quantity.index(mb)]
        else:
            ma, mb = quantity[1], quantity[2]
            res = ((price[quantity.index(ma)] - price[quantity.index(mb)]) / (ma - mb)) * (x - mb) + price[quantity.index(mb)]
            
    return res

interpolate(stdin)

[10, 25, 50, 100, 500]
X
100 500
[27.32, 23.13, 21.25, 18.0, 15.5]


6.125

In [99]:
a = [1,2,3,4,5,0,-1]
b = [-1,0,2,4,1,-2,3]

In [103]:
temp = [a for a in list(zip(a,b)) if a[1] > 0]

In [108]:
temp

[(3, 2), (4, 4), (5, 1), (-1, 3)]

In [107]:
np.array(temp)[:,0]

array([ 3,  4,  5, -1])

In [109]:
0 > -1.0

True

In [96]:
b = list(map(lambda x : x if x > 0 else 0, a))

In [94]:
zip()

[1, 2, 3, 4, 5, 0]

In [111]:
(42.84 - 31.48) / (25 - 10) * (2 - 25) + 42.84

25.421333333333333

In [114]:
x = 117
quantity = [10, 25, 61, 118, 334, 366, 468, 631, 804, 869, 970, 1000]
a = [i for i in quantity if x > i]

In [117]:
a[-1], quantity[quantity.index(a-1) + 1]

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [127]:
import pandas as pd

In [168]:
scores = np.array([10, 25, 25, 61, 118, 334, 366, 468])

a = [ score for score in enumerate( scores)]

In [134]:
score = pd.Series(scores)

In [135]:
score

0     10
1     25
2     25
3     61
4    118
5    334
6    366
7    468
dtype: int64

In [158]:
scores = np.sort(scores)[::-1]

In [171]:
rk = pd.Series(scores).rank(method = 'dense', ascending = False).astype(int).values
boards = list(zip(scores, rk))

In [172]:
boards

[(10, 7), (25, 6), (25, 6), (61, 5), (118, 4), (334, 3), (366, 2), (468, 1)]

In [174]:
alice = np.array([5,25,150,240])

In [180]:
np.array(boards)[:,1].max()

7

In [ ]:
for score in alice:
    for x in boards:
        if score >= x[0]:
            pass

In [ ]:
for score in alice:
    list(map(lambda x : x - score, boards))

In [186]:
boards

[(10, 7), (25, 6), (25, 6), (61, 5), (118, 4), (334, 3), (366, 2), (468, 1)]

In [194]:
ranking = []
for score in alice:
    loc = []
    for x in boards:
        if x[0] > score:
            loc.append(x[1]+1)
        else:
            continue
    ranking.append(max(loc))

In [198]:
ranking

[8, 6, 4, 4]

In [196]:
'\n'.join(map(str, ranking))

'8\n6\n4\n4'

In [205]:
scores = [100,100, 50, 40, 40, 20, 10]
alice = [5,25,50,120]

In [241]:
rk = pd.Series(scores).rank(method = 'dense', ascending = False).astype(int).values
boards = list(zip(scores, rk))
ranking = []
for score in alice:
    loc = []
    for x in boards:
        if x[0] > score:
            loc.append(x[1] + 1)
        elif score > max(np.array(boards)[:,0]):
            loc.append(1)
        else:
            continue
    ranking.append(max(loc))

In [242]:
ranking

[6, 4, 2, 1]

In [217]:
for x in boards:
    print(x)

(100, 1)
(100, 1)
(50, 2)
(40, 3)
(40, 3)
(20, 4)
(10, 5)


In [239]:
rk = pd.Series(scores).rank(method = 'dense', ascending = False).astype(int).values
boards = list(zip(scores, rk))
ranking = []
for score in alice:
    loc = []
    for x in boards:
        if score > x[0]:
            loc.append(x[1] - 1)
        elif score > max(np.array(boards)[:,0]):
            loc.append(1)
        else:
            continue
            
    if len(loc) == 0:
        loc.append(max(np.array(boards)[:,1]) + 1)
    ranking.append(max(loc))

In [240]:
ranking

[6, 4, 4, 4]

In [236]:
if len(loc) == 0:
    loc.append(max(np.array(boards)[:,1]) + 1)

In [237]:
loc

[6]

In [264]:
score = 35

In [254]:
boards

[(100, 1), (100, 1), (50, 2), (40, 3), (40, 3), (20, 4), (10, 5)]

In [250]:
scores

[100, 100, 50, 40, 40, 20, 10]

In [249]:
list(map(lambda x : x-score, scores))

[50, 50, 0, -10, -10, -30, -40]

In [265]:
list(map(lambda x : abs(x-score), scores)).index(min(list(map(lambda x : abs(x-score), scores))))

3

In [268]:
boards[3][1] + 1

4

In [299]:
score = 25
t = list(map(lambda x : x-score, scores))

In [300]:
t

[75, 75, 25, 15, 15, -5, -15]

In [308]:
min(t)

-15

In [294]:
list(map(lambda x : x if x > 0 else 0, t))

[75, 75, 25, 15, 15, 0, 0]

In [306]:
np.array(t) > 0

array([ True,  True,  True,  True,  True, False, False])

In [277]:
boards

[(100, 1), (100, 1), (50, 2), (40, 3), (40, 3), (20, 4), (10, 5)]

In [284]:
min(t)

5

In [285]:
t.index(min(t))

5

In [286]:
boards[5][1]

4

In [278]:
rk = pd.Series(scores).rank(method = 'dense', ascending = False).astype(int).values
boards = list(zip(scores, rk))
ranking = []
for score in alice:
    if score >= max(np.array(boards)[:,0]):
        loc = 1
    elif score < min(np.array(boards)[:,0]):
        loc = max(np.array(boards)[:,1])+1
    elif score == min(np.array(boards)[:,0]):
        loc = max(np.array(boards)[:,1])
    else:
        t = list(map(lambda x : abs(x-score), scores))
        q = t.index(min(t))
        if min(t) == 0:
            loc = boards[q][1]
        else:
            loc = boards[q][1]
    ranking.append(loc)
        

In [279]:
ranking

[6, 4, 2, 1]

In [ ]:
def climbingLeaderboard(scores, alice):
    rk = pd.Series(scores).rank(method = 'dense', ascending = False).astype(int).values
    boards = list(zip(scores, rk))
    ranking = []
    for score in alice:
        loc = []
        for x in boards:
            if score >= max(np.array(boards)[:,0]):
                loc.append(1)
                break
            elif score < min(np.array(boards)[:,0]):
                loc.append(max(np.array(boards)[:,1])+1)
                break
            elif x[0] > score:
                loc.append(x[1] + 1)
            else:
                continue
        ranking.append(max(loc))
    return ranking