In [1]:
import random
import numpy as np

In [37]:
n = int(input())
list = []
score = 0
for i in range(n):
    a = random.randint(1, 3)
    b = random.randint(1, 3)
    
    while a==b:
        b = random.randint(1, 3)
    
    c = random.randint(1, 3)
    
    value = [a,b,c]
    list.append(value)
    
    
    
list


    # 처음에 a에 동전이 있는 경우
    
    # 처음에 b에 동전이 있는 경우
    
    # 처음에 c에 동전이 있는 경우
        
    

 5


[[1, 3, 1], [1, 3, 2], [1, 2, 1], [1, 3, 1], [2, 1, 1]]

In [ ]:
n = int(input())
score = 0

a = random.randint(1, 3)
b = random.randint(1, 3)
while a==b:
    b = random.randint(1, 3)

c = random.randint(1, 3)

# 처음에 a에 동전이 있는 경우
if b == c:
    score = score + 1

# 처음에 b에 동전이 있는 경우


# 처음에 c에 동전이 있는 경우



print(a,b,c)
print(score,'\n')
    

In [151]:
temp2 = np.array([])

In [176]:
temp2 = np.array([0,0,0])
for i in range(3):
    a = np.random.randint(1,4)
    b = np.random.randint(1,4)
    while a==b:
        b = np.random.randint(1, 4)
    c = np.random.randint(1,4)

    temp = np.array([a,b,c])
    temp2 = np.vstack((temp2, temp))

temp2 = temp2[1:]

for i in range(len(tmep2)):
    # a(1)가 정답일때
    if temp2[i][0] == 1 or temp2[i][1] == 1



In [179]:
temp2

array([[1, 3, 1],
       [3, 1, 1],
       [3, 1, 3]])

In [180]:
len(temp2)

3

In [152]:
temp2 = np.concatenate((temp2, temp))
temp2

array([3., 2.])

In [153]:
temp

array([3, 2])

In [143]:
np.array([a,b])

array([1, 2])

## 2번

In [28]:
import numpy as np

r = int(input())

for q in range(r):
    
    n,s,k = input().split()
    n = int(n)
    s = int(s)
    k = int(k)
    
    ks = input().split()
    
    if k == 1:
        if abs(int(ks[0]) - s) == 0:
            print(1)
        else:
            print(0)
    else:
        ks = list(map(int,ks))
        ns = set(list(range(1,n)))
        ks = set(list(ks))

        f = []
        for i in ns.difference(ks):
            value = abs(i - s)
            f.append(value)
        print(min(f))
            

 1
 10 5 3
 1 2 3


0


## 3번

In [ ]:
import pandas as pd
from itertools import combinations

In [128]:
n = int(input())
ices = input().split()

df = pd.DataFrame(ices, columns = ['raw'])
df[['raw']] = df[['raw']].astype(int)

df['3의배수'] = df['raw'].apply(lambda a,b,c: a if x % 3 == 0 elif )
# df['나1'] = df.loc[df['3의배수'] == 0, 'raw'].apply(lambda a,b,c: x if x % 3 == 1 else 0)
# df['나2'] = df['raw'].apply(lambda x: x if x % 3 == 2 else 0)

ice_raw = df.loc[df['3의배수'] != 0, '3의배수']
ice_1 = len(list(combinations(ice_raw,2)))
ice_2 = len(df.loc[df['나1'] != 0, '나1'].unique())
ice_3 = len(df.loc[df['나2'] != 0, '나2'].unique())

value = ice_1 + (ice_2 * ice_3)
print(value)

SyntaxError: invalid syntax (<ipython-input-128-d15e2134990d>, line 7)

In [2]:
n = int(input())
a = input()
ices = list(map(int,a.split()))
ice_1 = []
ice_2 = []
ice_3 = []

for ice in ices:
    if int(ice) % 3 == 1:
        ice_1.append(ice)
    elif int(ice) % 3 == 2:
        ice_2.append(ice)
    else:
        ice_3.append(ice)

ice_3 = len(list(combinations(ice_3,2)))
ice_1 = len(ice_1)
ice_2 = len(ice_2)

value = ice_3 + (ice_1 * ice_2)
print(value)


 1
 1 2 3


NameError: name 'combinations' is not defined

In [144]:
n = int(input())
ices = input().split()
ice_temp = []
ice_1 = []
ice_2 = []
ice_3 = []

for ice in ices:
    if int(ice) % 3 == 0:
        ice_1.append(ice)
    else:
        ice_temp.append(ice)

ice_temp = set(ice_temp)

for ice in ice_temp:
    if int(ice) % 3 == 2:
        ice_2.append(ice)
    else:
        ice_3.append(ice)
        
        
ice_1 = len(list(combinations(ice_1,2)))
ice_2 = len(ice_2)
ice_3 = len(ice_3)

value = ice_1 + (ice_2 * ice_3)
print(value)


 5
 1 4 2 3 3


{'2', '1', '4'}
3


In [1]:
n = int(input())
a= input()
b = []
b = list(map(int,a.split()))
count = 0
count1 = 0
count2 = 0
for i in range(n):
    if b[i]%3==0:
        count =count+1
    elif b[i]%3==1:
        count1 = count1 + 1
    elif b[i]%3==2:
        count2 = count2 + 1
k=0
for j in range(count):
    k += j
print(k+(count1*count2))

KeyboardInterrupt: 